### ISSUE TITLE
Incompatible mods found!

### ISSUE THREAD

**Issue by breelock** [PlayReissLP/Continuity#2]
![image](https://github.com/user-attachments/assets/8eede99d-5d7d-4006-abde-54561d184eb9)
logs:
```
[18:30:27] [main/INFO]: Loading Minecraft 1.16.5 with Fabric Loader 0.15.11
[18:30:27] [main/WARN]: Mod resolution failed
[18:30:27] [main/INFO]: Immediate reason: [HARD_DEP_INCOMPATIBLE_PRESELECTED continuity 0.1.0+1.16 {depends java @ [<=8]}, ROOT_FORCELOAD_SINGLE continuity 0.1.0+1.16]
[18:30:27] [main/INFO]: Reason: [HARD_DEP continuity 0.1.0+1.16 {depends java @ [<=8]}]
[18:30:27] [main/INFO]: Fix: add [], remove [], replace [[java 17] -> add:java 8 ([[8,8]])]
[18:30:27] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace 'OpenJDK 64-Bit Server VM' (java) 17 with version 8.
More details:
	 - Mod 'Continuity' (continuity) 0.1.0+1.16 requires version 8 or earlier of 'OpenJDK 64-Bit Server VM' (java), but only the wrong version is present: 17!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
```
I have installed the following mods:
![image](https://github.com/user-attachments/assets/3e48427d-f0a2-4cb1-8257-21cac1f89097)
As it says in the error, I installed jdk 8. But it didn't help. Maybe I installed the wrong jdk?
![image](https://github.com/user-attachments/assets/2267a8d7-8fcf-40a9-bb81-464d2088a220)
What am I doing wrong? Help me, please.

**Comment by PlayReissLP** [comment]
@breelock Hmm, are you using the normal Minecraft Launcher? If so, try changing the Java version inside the Launcher. Just add the path of your OpenJDK there.

**Comment by breelock** [comment]
I'm using tl legacy launcher, in the settings I specified the path to jdk 8:
![image](https://github.com/user-attachments/assets/ed5f2dfb-f64b-40e2-aad3-3f5aeaf8147a)
Then installed the Indium mod:
![image](https://github.com/user-attachments/assets/47eb1ade-f9b3-4c44-9b39-18192c22be5f)
And mod build-it resource packs:
![image](https://github.com/user-attachments/assets/42222622-2037-4ebe-a130-bbce791785de)
And it worked! Thank you so much!
![image](https://github.com/user-attachments/assets/81f01095-3db3-4131-8c26-f33014757f38)
